---
- hosts: db
  become: true
  tasks:
    - name: Ensure MariaDB-server is installed
      ansible.builtin.package:
        name: mariadb-server
        state: present

    - name: Ensure mariadb service is enabled at boot
      ansible.builtin.systemd:
        name: mariadb
        enabled: yes
      register: enable_result

    - name: Ensure MariaDB service is enabled and started
      ansible.builtin.service:
        name: mariadb
        enabled: true
        state: started
