---
- hosts: db
  become: true
  tasks:
    - name: copy .md files to deploy
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: /home/deploy
        owner: deploy
        mode: "0644"
      with_fileglob: "../files/*.md"
